### ISSUE TITLE
Feature Suggestion: Add setting for whether or not the xmlns:media namespace code snippet is enabled or not.

### ISSUE THREAD

**Issue by KZeni** [wearerequired/wp-feed-post-thumbnail#20]
I have a site that also has YoastSEO's Video add-on which then also adds the xmlns:media entry for search.yahoo.com/mrss. However, these then doubled-up and resulted in invalid code that FeedPress & other feed readers couldn't parse as a result.

Thankfully YoastSEO's Video extension has a "Disable Media RSS Enhancement" setting which prevents their output of this in the RSS feed.

However, I'm thinking it might be helpful if this is surfaced via this plugin as well just in case there are any other conflicting plugins out there where this can be the plugin offering the setting that's needed. Also, it might help people resolve the issue quicker since one might think to check this plugin before YoastSEO Video or whatever other plugins they may have.

Also posted this at https://wordpress.org/support/topic/feature-suggestion-add-setting-for-whether-or-not-the-xmlnsmedia-namespace-cod/ as well for better visibility/discussion amongst the appropriate people.

Thanks,
Kurt

**Comment by grappler** [comment]
Hi Kurt

Thank you for the suggestion.

I have been thinking how we could show a potential conflict. The function `has_action('rss2_ns')` could tell us if multiple functions are adding an namespace but it would be a bit more complicated to figure out which plugins and what namespace they are adding.

If I had to debug the problem I would have noticed that there are two of the same namespace and the searched through all of the plugins for that namespace. Based upon that I could disable the conflicting plugins.

As this is the first conflict that we have heard of I will keep this issue open to see there is any further feedback/conflicts and based on that decide what the best path forward is.

**Comment by KZeni** [comment]
I wouldn't want to resort to disabling plugins as your plugin does something that the others don't & vice-versa. Ideally, the conflict could be addressed by either:

1. Avoiding it autonomously through code (checking if it exists already or not before adding as it seems like you've mentioned... preventing the duplicate)
2. Doing the YoastSEO Video approach of just having a setting which allows that to be turned off (also then preventing the duplicate code that would otherwise cause it to become an invalid feed that some services & apps outright refuse to work with.)

Option 2 isn't the smoothest behavior, but at least the functionality-breaking conflict can be avoided rather quickly & simply rather than needing to just not use the plugin. Plus, it's definitely the fastest option to implement, I'd imagine.

Thanks for the response 🙂

**Comment by farmerpaul** [comment]
Confirmed that we're encountering the same conflict, which is preventing the blog feed from being fetched using SimplePie (apparently not a very forgiving XML parser). Thanks in advance to whomever has time to look into this, but in the meantime, thank you @KZeni for suggesting a workaround.

**Comment by grappler** [comment]
@farmerpaul Just to confirm, the conflict is between this plugin and Yoast SEO Video add-on?

**Comment by farmerpaul** [comment]
@grappler: Yes, exactly – [YoastSEO's Video add-on](https://yoast.com/wordpress/plugins/video-seo/).

**Comment by KZeni** [comment]
While this is also regarding Yoast SEO's Video plugin, this could potentially be with any plugin that adds a namespace to the feed like that (Yoast just happens to be popular, it seems.) At that point, this plugin is un-budging in this regard & potentially leaving things broken unless completely disabled, but Yoast thankfully has a method to disable adding the media tags to the feed (which users might not think to check, might want this plugin to prevent the issue, and/or might not be something that's available with other plugins.)

As such, it'd still be ideal if one of the two (or both) items included in my comment above (https://github.com/wearerequired/wp-feed-post-thumbnail/issues/20#issuecomment-755738645) are implemented to prevent the need for this topic to still be active w/ more people stumbling across it.

**Comment by grappler** [comment]
I am looking into adding a setting to disable the namespace but I only want to show the setting if multiple plugins are hooking into `rss2_ns`. So that I could I test it with Yoast Video Addon, could you send me a copy of the plugin to ulrich @ required.ch?

Here is the new settings copy. Let me know if that makes sense.
![image](https://user-images.githubusercontent.com/1785641/111954748-d9706680-8ae8-11eb-8add-876e7c95203f.png)

**Comment by KZeni** [comment]
@grappler Look for an email from me in that regard.

I think that setting makes sense. Thanks!
